# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.provider "virtualbox" do |v|
        v.memory = 3072
        v.cpus = 4
    end
  
    config.vm.define "deep-thought" do |v|
        v.vm.box = "hashicorp/precise64"
        v.vm.network :private_network, ip: "192.168.66.66"
        v.vm.provision "shell", path: "build/provision-deep-thought.sh"
        v.vm.synced_folder ".", "/vagrant", type: "nfs"
        v.vm.synced_folder "../src", "/var/www", type: "nfs"
    end
  
end
